# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createMergeMatrix <- function(n, prune_res) {
    .Call('_Rmergetrees_createMergeMatrix', PACKAGE = 'Rmergetrees', n, prune_res)
}

hcToPath_cpp <- function(successives_steps, merge1, order1, n) {
    .Call('_Rmergetrees_hcToPath_cpp', PACKAGE = 'Rmergetrees', successives_steps, merge1, order1, n)
}

match_func_int <- function(x, y) {
    .Call('_Rmergetrees_match_func_int', PACKAGE = 'Rmergetrees', x, y)
}

pruneSplits <- function(listSetRules, orderRules, n, p) {
    .Call('_Rmergetrees_pruneSplits', PACKAGE = 'Rmergetrees', listSetRules, orderRules, n, p)
}

